### ISSUE TITLE
[FEATURE REQUEST] Remove Background

### ISSUE THREAD

**Issue by JohnnyPlayy** [Luncaaa/AdvancedDisplays#1]
### Describe what you would like to see in a future version.

This plugin is lovely, but it seems like there is no way to remove the background.

![image](https://github.com/user-attachments/assets/5483adc2-dbdf-4fd5-86cd-ea3c6e8b0288)
An example!

**Comment by Luncaaa** [comment]
> ### Describe what you would like to see in a future version.
> This plugin is lovely, but it seems like there is no way to remove the background.

Hello Johny! To remove the background, set the `defaultBackground` setting to false and set alpha in the `backgroundColor` setting to 0. That should make the background invisible. You can also set `shadowed` to false to remove the text's shadows

Thanks for your comments! Let me know if this is what you meant by removing the background

**Comment by JohnnyPlayy** [comment]
It worked perfectly.
