### ISSUE TITLE
[FEATURE REQUEST] Adding "If player does not have a permission" condition

### ISSUE THREAD

**Issue by bxnAcc** [Luncaaa/AdvancedDisplays#2]
### Describe what you would like to see in a future version.

Basicly it would be nice to not only have the possibility to show players a displays if a player has a permission, but also have the option to only show the display to players wich don't have a specific permission. Maybe for options you would just add a ! infront of the permission (!permission.example)

**Comment by Luncaaa** [comment]
Hello @bxnAcc , thanks for your suggestion! I have implemeted it in the latest dev build, which you can download [here](https://github.com/Luncaaa/AdvancedDisplays/releases/tag/dev).

You'll need to run the conversion command (remember to make a backup!) and it'll add a new setting to the displays' config file: `hide-permission`. If it's not set to "none" and the player has that permission, they won't see the display. Basically, the player will need to have the permission from the `permission` setting and not have the one from `hide-permission`

Let me know if it works as expected or if you need anything else ;)
